# Generated by Django 4.1.3 on 2022-11-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workimages',
            name='display_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
