# Generated by Django 4.1.3 on 2022-12-02 14:16

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0003_invoice_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workimages',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(help_text='img', upload_to='images/', verbose_name='img'),
        ),
    ]
